### ISSUE TITLE
Design Fixes

### ISSUE THREAD

**Issue by almadegoma** [juliogarciag/scrabble-scorer#6]
**1. Game table border:**
Now: 
  ![screen shot 2016-12-23 at 20 33 41](https://cloud.githubusercontent.com/assets/24687950/21464593/5b91344c-c94f-11e6-821c-186dcf02861a.png)
Expected: https://app.zeplin.io/project.html#pid=5803a2d8aeb1fd346e4796ed&sid=5803a50ff65bcc0414d07e51

**2. Replace RESET GAME and FINISH GAME buttons**
Now:
![screen shot 2016-12-23 at 20 38 03](https://cloud.githubusercontent.com/assets/24687950/21464608/f7c06496-c94f-11e6-9b96-1d992be4e26d.png)
Expected: https://app.zeplin.io/project.html#pid=5803a2d8aeb1fd346e4796ed&sid=5803a50ff65bcc0414d07e51

**3. Replace emojis**
Now:
![screen shot 2016-12-23 at 20 41 21](https://cloud.githubusercontent.com/assets/24687950/21464613/31517722-c950-11e6-898c-8162f955adbe.png)
Expected: https://app.zeplin.io/project.html#pid=5803a2d8aeb1fd346e4796ed&sid=5803a50ff65bcc0414d07e51

**4. Edit icon is not aligned correctly**
Now:
![screen shot 2016-12-23 at 20 42 56](https://cloud.githubusercontent.com/assets/24687950/21464625/94af3a84-c950-11e6-9af2-01a3f855265e.png)
Expected: https://app.zeplin.io/project.html#pid=5803a2d8aeb1fd346e4796ed&sid=5803a50ff65bcc0414d07e51

**Comment by almadegoma** [comment]
It only needs to complete N3. The emojis are ready.

**Comment by juliogarciag** [comment]
These changes are ready!
